import mongoose, { Document, Schema, Types } from "mongoose";

/*
 * The category of the generated workout plan.
 */
export type GeneratedWorkoutPlanCategory =
  | "strength"
  | "hypertrophy"
  | "endurance"
  | "general_fitness"
  | "mobility"
  | "weight_loss";

/*
 * The current lifecycle status of the plan.
 */
export type GeneratedWorkoutPlanStatus =
  | "active"
  | "completed"
  | "archived";

/*
 * The trainee data used when Gemini generated the plan.
 *
 * We save a snapshot because the trainee may change their
 * profile after the plan has already been generated.
 */
export interface IGeneratedWorkoutProfileSnapshot {
  fitnessLevel: "beginner" | "intermediate" | "advanced";
  goals: string[];
  weeklyWorkouts: number;
  height?: number;
  weight?: number;
  age?: number;
  gender?: string;
  availableEquipment: string[];
  medicalConditions: string[];
  medicalNotes?: string;
  preferredWorkoutTime?: string;
  sessionDurationMinutes?: number;
}

/*
 * One exercise inside a generated workout day.
 */
export interface IGeneratedWorkoutExercise {
  _id?: Types.ObjectId;
  order: number;
  name: string;
  sets?: number;
  reps?: string;
  durationSec?: number;
  restSec?: number;
  equipment: string;
  notes?: string;
}

/*
 * One day inside the generated plan.
 */
export interface IGeneratedWorkoutDay {
  _id?: Types.ObjectId;
  dayNumber: number;
  title: string;
  restDay: boolean;
  durationMinutes: number;
  exercises: IGeneratedWorkoutExercise[];
}

/*
 * A complete workout plan generated by Gemini.
 */
export interface IGeneratedWorkoutPlan extends Document {
  userId: Types.ObjectId;
  title: string;
  description: string;
  category: GeneratedWorkoutPlanCategory;
  difficulty: number;
  durationWeeks: number;
  workoutDaysPerWeek: number;
  equipment: string[];
  status: GeneratedWorkoutPlanStatus;
  requiresProfessionalReview: boolean;
  profileSnapshot: IGeneratedWorkoutProfileSnapshot;
  days: IGeneratedWorkoutDay[];
  createdAt: Date;
  updatedAt: Date;
}

/*
 * Exercise schema.
 */
const GeneratedWorkoutExerciseSchema =
  new Schema<IGeneratedWorkoutExercise>(
    {
      order: {
        type: Number,
        required: true,
        min: 1,
      },

      name: {
        type: String,
        required: true,
        trim: true,
      },

      sets: {
        type: Number,
        min: 1,
      },

      /*
       * reps is a string because Gemini may generate:
       * "8", "8-10", "AMRAP", or "30 seconds".
       */
      reps: {
        type: String,
        trim: true,
      },

      durationSec: {
        type: Number,
        min: 0,
      },

      restSec: {
        type: Number,
        min: 0,
      },

      equipment: {
        type: String,
        default: "none",
        trim: true,
      },

      notes: {
        type: String,
        trim: true,
      },
    },
    {
      _id: true,
    }
  );

/*
 * Workout-day schema.
 */
const GeneratedWorkoutDaySchema =
  new Schema<IGeneratedWorkoutDay>(
    {
      dayNumber: {
        type: Number,
        required: true,
        min: 1,
      },

      title: {
        type: String,
        required: true,
        trim: true,
      },

      restDay: {
        type: Boolean,
        required: true,
        default: false,
      },

      durationMinutes: {
        type: Number,
        required: true,
        min: 0,
      },

      exercises: {
        type: [GeneratedWorkoutExerciseSchema],
        default: [],
      },
    },
    {
      _id: true,
    }
  );

/*
 * A rest day cannot contain exercises.
 * A workout day must contain at least one exercise.
 */
GeneratedWorkoutDaySchema.pre("validate", function () {
  if (this.restDay && this.exercises.length > 0) {
    throw new Error("A rest day cannot contain exercises");
  }

  if (!this.restDay && this.exercises.length === 0) {
    throw new Error(
      "A workout day must contain at least one exercise"
    );
  }
});

/*
 * Snapshot of the trainee profile.
 */
const GeneratedWorkoutProfileSnapshotSchema =
  new Schema<IGeneratedWorkoutProfileSnapshot>(
    {
      fitnessLevel: {
        type: String,
        enum: ["beginner", "intermediate", "advanced"],
        required: true,
      },

      goals: {
        type: [String],
        default: [],
      },

      weeklyWorkouts: {
        type: Number,
        required: true,
        min: 1,
        max: 7,
      },

      height: {
        type: Number,
        min: 1,
      },

      weight: {
        type: Number,
        min: 1,
      },

      age: {
        type: Number,
        min: 1,
      },

      gender: {
        type: String,
      },

      availableEquipment: {
        type: [String],
        default: [],
      },

      medicalConditions: {
        type: [String],
        default: [],
      },

      medicalNotes: {
        type: String,
      },

      preferredWorkoutTime: {
        type: String,
      },

      sessionDurationMinutes: {
        type: Number,
      },
    },
    {
      _id: false,
    }
  );

/*
 * Main generated workout-plan schema.
 */
const GeneratedWorkoutPlanSchema =
  new Schema<IGeneratedWorkoutPlan>(
    {
      userId: {
        type: Schema.Types.ObjectId,
        ref: "Users",
        required: true,
        index: true,
      },

      title: {
        type: String,
        required: true,
        trim: true,
      },

      description: {
        type: String,
        required: true,
        trim: true,
      },

      category: {
        type: String,
        enum: [
          "strength",
          "hypertrophy",
          "endurance",
          "general_fitness",
          "mobility",
          "weight_loss",
        ],
        required: true,
      },

      difficulty: {
        type: Number,
        required: true,
        min: 1,
        max: 5,
      },

      durationWeeks: {
        type: Number,
        required: true,
        min: 1,
        max: 12,
      },

      workoutDaysPerWeek: {
        type: Number,
        required: true,
        min: 1,
        max: 7,
      },

      equipment: {
        type: [String],
        default: [],
      },

      status: {
        type: String,
        enum: ["active", "completed", "archived"],
        default: "active",
      },

      requiresProfessionalReview: {
        type: Boolean,
        default: false,
      },

      profileSnapshot: {
        type: GeneratedWorkoutProfileSnapshotSchema,
        required: true,
      },

      days: {
        type: [GeneratedWorkoutDaySchema],
        required: true,
        default: [],
      },
    },
    {
      collection: "GeneratedWorkoutPlans",
      versionKey: false,
      timestamps: true,
    }
  );

/*
 * Validate the full plan before saving.
 */
GeneratedWorkoutPlanSchema.pre("validate", function () {
  const workoutDays = this.days.filter(
    (day) => !day.restDay
  );

  /*
   * The amount of actual workout days must match
   * the trainee's requested workouts per week.
   */
  if (
    workoutDays.length !==
    this.workoutDaysPerWeek
  ) {
    throw new Error(
      "The number of workout days must match workoutDaysPerWeek"
    );
  }

  /*
   * Reject duplicate day numbers.
   */
  const dayNumbers = this.days.map(
    (day) => day.dayNumber
  );

  if (
    new Set(dayNumbers).size !== dayNumbers.length
  ) {
    throw new Error(
      "The workout plan contains duplicate day numbers"
    );
  }

  /*
   * Reject duplicate exercise order values
   * inside the same workout day.
   */
  for (const day of this.days) {
    const exerciseOrders = day.exercises.map(
      (exercise) => exercise.order
    );

    if (
      new Set(exerciseOrders).size !==
      exerciseOrders.length
    ) {
      throw new Error(
        `Day ${day.dayNumber} contains duplicate exercise order values`
      );
    }
  }
});

/*
 * Only one active generated plan is allowed
 * for the same trainee.
 */
GeneratedWorkoutPlanSchema.index(
  {
    userId: 1,
    status: 1,
  },
  {
    unique: true,
    partialFilterExpression: {
      status: "active",
    },
  }
);

/*
 * Reuse the model if nodemon reloads the project.
 */
const GeneratedWorkoutPlan =
  mongoose.models.GeneratedWorkoutPlans ||
  mongoose.model<IGeneratedWorkoutPlan>(
    "GeneratedWorkoutPlans",
    GeneratedWorkoutPlanSchema
  );

export default GeneratedWorkoutPlan;